root: true
env:
  browser: true
  node: true
  es2021: true
globals:
  remote: true
  exit: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  semi: [error, always]
